from typing import Dict, List


ASSESSMENT_QUESTIONS: Dict[str, List[dict]] = {
    "Algorithms": [
        {
            "id": 1,
            "skill": "Algorithms",
            "topic": "Searching",
            "question": "What is the time complexity of linear search in the worst case?",
            "options": ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
            "answer": "O(n)",
        },
        {
            "id": 2,
            "skill": "Algorithms",
            "topic": "Sorting",
            "question": "Which sorting algorithm has an average time complexity of O(n log n)?",
            "options": ["Bubble Sort", "Merge Sort", "Linear Search", "Selection Sort"],
            "answer": "Merge Sort",
        },
        {
            "id": 3,
            "skill": "Algorithms",
            "topic": "Binary Search",
            "question": "Binary search can be directly applied when the data is:",
            "options": [
                "Unsorted",
                "Stored randomly",
                "Sorted",
                "Only stored in a linked list",
            ],
            "answer": "Sorted",
        },
        {
            "id": 4,
            "skill": "Algorithms",
            "topic": "Greedy Algorithms",
            "question": "A greedy algorithm makes decisions by:",
            "options": [
                "Always choosing the locally optimal option",
                "Trying every possible solution",
                "Using only recursion",
                "Randomly selecting an option",
            ],
            "answer": "Always choosing the locally optimal option",
        },
        {
            "id": 5,
            "skill": "Algorithms",
            "topic": "Dynamic Programming",
            "question": "Dynamic programming is mainly useful when a problem has:",
            "options": [
                "Only one possible solution",
                "Overlapping subproblems and optimal substructure",
                "No subproblems",
                "Only sorting operations",
            ],
            "answer": "Overlapping subproblems and optimal substructure",
        },
        {
            "id": 6,
            "skill": "Searching",
            "topic": "Searching",
            "question": "What is the worst-case time complexity of binary search?",
            "options": ["O(n)", "O(log n)", "O(n²)", "O(1)"],
            "answer": "O(log n)",
        },
        {
            "id": 7,
            "skill": "Sorting",
            "topic": "Sorting",
            "question": "Which sorting algorithm repeatedly swaps adjacent elements when they are in the wrong order?",
            "options": ["Merge Sort", "Quick Sort", "Bubble Sort", "Heap Sort"],
            "answer": "Bubble Sort",
        },
        {
            "id": 8,
            "skill": "Dynamic Programming",
            "topic": "Dynamic Programming",
            "question": "Which technique stores results of previously solved subproblems?",
            "options": ["Memoization", "Backtracking", "Hashing only", "Linear scanning"],
            "answer": "Memoization",
        },
        {
            "id": 9,
            "skill": "Greedy Algorithms",
            "topic": "Greedy Algorithms",
            "question": "Which problem is commonly solved using a greedy strategy?",
            "options": [
                "Activity Selection",
                "Matrix Chain Multiplication",
                "Longest Common Subsequence",
                "Floyd-Warshall",
            ],
            "answer": "Activity Selection",
        },
        {
            "id": 10,
            "skill": "Algorithms",
            "topic": "Sorting",
            "question": "What is the average-case time complexity of quicksort?",
            "options": ["O(n)", "O(log n)", "O(n log n)", "O(n²)"],
            "answer": "O(n log n)",
        },
    ],

    "Data Structures": [
        {
            "id": 11,
            "skill": "Data Structures",
            "topic": "Strings",
            "question": "Which data structure is commonly used to store a sequence of characters?",
            "options": ["String", "Stack", "Graph", "Tree"],
            "answer": "String",
        },
        {
            "id": 12,
            "skill": "Data Structures",
            "topic": "Linked Lists",
            "question": "Which structure does a singly linked-list node typically contain?",
            "options": [
                "Only data",
                "Data and a pointer to the next node",
                "Only two arrays",
                "Only a stack",
            ],
            "answer": "Data and a pointer to the next node",
        },
        {
            "id": 13,
            "skill": "Data Structures",
            "topic": "Stacks and Queues",
            "question": "Which principle does a stack follow?",
            "options": ["FIFO", "LIFO", "Random access", "Priority only"],
            "answer": "LIFO",
        },
        {
            "id": 14,
            "skill": "Data Structures",
            "topic": "Stacks and Queues",
            "question": "Which principle does a queue follow?",
            "options": ["LIFO", "FIFO", "Random access", "Depth-first"],
            "answer": "FIFO",
        },
        {
            "id": 15,
            "skill": "Data Structures",
            "topic": "Trees",
            "question": "A binary tree node can have at most how many children?",
            "options": ["1", "2", "3", "Unlimited"],
            "answer": "2",
        },
        {
            "id": 16,
            "skill": "Data Structures",
            "topic": "Graphs",
            "question": "Which algorithm is commonly used for breadth-first traversal?",
            "options": ["Queue", "Stack", "Heap", "Hash table"],
            "answer": "Queue",
        },
        {
            "id": 17,
            "skill": "Data Structures",
            "topic": "Trees",
            "question": "Which traversal of a binary search tree produces sorted order?",
            "options": ["Preorder", "Postorder", "Inorder", "Level order"],
            "answer": "Inorder",
        },
        {
            "id": 18,
            "skill": "Data Structures",
            "topic": "Graphs",
            "question": "Which data structure is commonly used for depth-first search?",
            "options": ["Queue", "Stack", "Priority queue", "Array only"],
            "answer": "Stack",
        },
        {
            "id": 19,
            "skill": "Data Structures",
            "topic": "Linked Lists",
            "question": "What is the typical time complexity to insert a node at the beginning of a linked list?",
            "options": ["O(1)", "O(log n)", "O(n)", "O(n²)"],
            "answer": "O(1)",
        },
        {
            "id": 20,
            "skill": "Data Structures",
            "topic": "Trees",
            "question": "Which data structure is best suited for representing hierarchical data?",
            "options": ["Tree", "Queue", "Stack", "Array only"],
            "answer": "Tree",
        },
    ],

    "Python": [
        {
            "id": 21,
            "skill": "Python",
            "topic": "Functions and Modules",
            "question": "Which keyword is used to define a function in Python?",
            "options": ["func", "define", "def", "function"],
            "answer": "def",
        },
        {
            "id": 22,
            "skill": "Python",
            "topic": "Functions and Modules",
            "question": "Which keyword is used to import a Python module?",
            "options": ["include", "import", "using", "require"],
            "answer": "import",
        },
        {
            "id": 23,
            "skill": "Python",
            "topic": "OOP",
            "question": "Which keyword refers to the current object inside a Python class method?",
            "options": ["this", "self", "current", "object"],
            "answer": "self",
        },
        {
            "id": 24,
            "skill": "Python",
            "topic": "Exception Handling",
            "question": "Which block is used to handle an exception in Python?",
            "options": ["catch", "except", "handle", "error"],
            "answer": "except",
        },
        {
            "id": 25,
            "skill": "Python",
            "topic": "OOP",
            "question": "Which method is commonly used as a constructor in a Python class?",
            "options": ["__start__", "__create__", "__init__", "__newclass__"],
            "answer": "__init__",
        },
        {
            "id": 26,
            "skill": "Python",
            "topic": "Exception Handling",
            "question": "Which block executes whether an exception occurs or not?",
            "options": ["except", "finally", "catch", "raise"],
            "answer": "finally",
        },
        {
            "id": 27,
            "skill": "Python",
            "topic": "Functions and Modules",
            "question": "Which Python data type is immutable?",
            "options": ["List", "Dictionary", "Set", "Tuple"],
            "answer": "Tuple",
        },
        {
            "id": 28,
            "skill": "Python",
            "topic": "OOP",
            "question": "Which concept allows a child class to reuse functionality from a parent class?",
            "options": ["Inheritance", "Iteration", "Compilation", "Indexing"],
            "answer": "Inheritance",
        },
        {
            "id": 29,
            "skill": "Python",
            "topic": "Functions and Modules",
            "question": "Which symbol is used to create a comment in Python?",
            "options": ["//", "#", "/*", "--"],
            "answer": "#",
        },
        {
            "id": 30,
            "skill": "Python",
            "topic": "Exception Handling",
            "question": "Which keyword can be used to manually raise an exception?",
            "options": ["throw", "raise", "error", "exception"],
            "answer": "raise",
        },
    ],

    "Java": [
        {
            "id": 31,
            "skill": "Java",
            "topic": "Exception Handling",
            "question": "Which keyword is used to explicitly throw an exception in Java?",
            "options": ["throws", "throw", "raise", "error"],
            "answer": "throw",
        },
        {
            "id": 32,
            "skill": "Java",
            "topic": "Exception Handling",
            "question": "Which block is normally used to handle an exception?",
            "options": ["try", "catch", "finally", "throw"],
            "answer": "catch",
        },
        {
            "id": 33,
            "skill": "Java",
            "topic": "Multithreading",
            "question": "Which method starts execution of a Java thread?",
            "options": ["run()", "start()", "execute()", "begin()"],
            "answer": "start()",
        },
        {
            "id": 34,
            "skill": "Java",
            "topic": "Multithreading",
            "question": "Which interface can be implemented to define a task for a thread?",
            "options": ["Runnable", "Threadable", "Executor", "Process"],
            "answer": "Runnable",
        },
        {
            "id": 35,
            "skill": "Java",
            "topic": "Interview Practice",
            "question": "Which principle allows a class to have multiple forms through method overriding?",
            "options": ["Encapsulation", "Polymorphism", "Inheritance only", "Compilation"],
            "answer": "Polymorphism",
        },
        {
            "id": 36,
            "skill": "Java",
            "topic": "Exception Handling",
            "question": "Which block is generally executed regardless of whether an exception occurs?",
            "options": ["catch", "finally", "throw", "throws"],
            "answer": "finally",
        },
        {
            "id": 37,
            "skill": "Java",
            "topic": "Multithreading",
            "question": "Which method pauses a thread for a specified amount of time?",
            "options": ["waitTime()", "sleep()", "pause()", "hold()"],
            "answer": "sleep()",
        },
        {
            "id": 38,
            "skill": "Java",
            "topic": "Interview Practice",
            "question": "Which keyword is used to inherit from a class in Java?",
            "options": ["implements", "inherits", "extends", "super"],
            "answer": "extends",
        },
        {
            "id": 39,
            "skill": "Java",
            "topic": "Interview Practice",
            "question": "Which collection does not allow duplicate elements?",
            "options": ["List", "Set", "ArrayList", "LinkedList"],
            "answer": "Set",
        },
        {
            "id": 40,
            "skill": "Java",
            "topic": "Multithreading",
            "question": "What is the purpose of synchronization in multithreading?",
            "options": [
                "Increase memory usage",
                "Control access to shared resources",
                "Create more threads",
                "Stop compilation",
            ],
            "answer": "Control access to shared resources",
        },
    ],

    "C++": [
        {
            "id": 41,
            "skill": "C++",
            "topic": "Pointers and References",
            "question": "Which operator is used to obtain the address of a variable in C++?",
            "options": ["*", "&", "#", "@"],
            "answer": "&",
        },
        {
            "id": 42,
            "skill": "C++",
            "topic": "Pointers and References",
            "question": "Which symbol is used to dereference a pointer?",
            "options": ["&", "*", "%", "#"],
            "answer": "*",
        },
        {
            "id": 43,
            "skill": "C++",
            "topic": "Problem Solving",
            "question": "Which container follows the LIFO principle?",
            "options": ["queue", "stack", "vector", "map"],
            "answer": "stack",
        },
        {
            "id": 44,
            "skill": "C++",
            "topic": "Problem Solving",
            "question": "Which STL container stores elements in contiguous memory and can grow dynamically?",
            "options": ["vector", "stack", "queue", "set"],
            "answer": "vector",
        },
        {
            "id": 45,
            "skill": "C++",
            "topic": "Interview Practice",
            "question": "Which feature allows the same function name to have different parameter lists?",
            "options": ["Overloading", "Overriding", "Inheritance", "Encapsulation"],
            "answer": "Overloading",
        },
        {
            "id": 46,
            "skill": "C++",
            "topic": "Pointers and References",
            "question": "A reference in C++ is:",
            "options": [
                "An alias for another variable",
                "A new object always",
                "A pointer that must be null",
                "A function",
            ],
            "answer": "An alias for another variable",
        },
        {
            "id": 47,
            "skill": "C++",
            "topic": "Problem Solving",
            "question": "Which STL container stores key-value pairs?",
            "options": ["vector", "map", "stack", "queue"],
            "answer": "map",
        },
        {
            "id": 48,
            "skill": "C++",
            "topic": "Interview Practice",
            "question": "Which concept hides implementation details from the user?",
            "options": ["Encapsulation", "Iteration", "Compilation", "Recursion"],
            "answer": "Encapsulation",
        },
        {
            "id": 49,
            "skill": "C++",
            "topic": "Problem Solving",
            "question": "Which STL algorithm can be used to sort a range?",
            "options": ["sort()", "order()", "arrange()", "sequence()"],
            "answer": "sort()",
        },
        {
            "id": 50,
            "skill": "C++",
            "topic": "Interview Practice",
            "question": "Which OOP feature allows a derived class to provide a specific implementation of a base class method?",
            "options": ["Overriding", "Overloading", "Templates", "Namespaces"],
            "answer": "Overriding",
        },
    ],

    "SQL": [
        {
            "id": 51,
            "skill": "SQL",
            "topic": "Joins",
            "question": "Which JOIN returns matching rows from both tables?",
            "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "CROSS JOIN"],
            "answer": "INNER JOIN",
        },
        {
            "id": 52,
            "skill": "SQL",
            "topic": "Joins",
            "question": "Which JOIN returns all rows from the left table and matching rows from the right table?",
            "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "SELF JOIN"],
            "answer": "LEFT JOIN",
        },
        {
            "id": 53,
            "skill": "SQL",
            "topic": "Aggregate Functions",
            "question": "Which function calculates the average of numeric values?",
            "options": ["SUM()", "AVG()", "COUNT()", "TOTAL()"],
            "answer": "AVG()",
        },
        {
            "id": 54,
            "skill": "SQL",
            "topic": "Aggregate Functions",
            "question": "Which clause groups rows with the same values?",
            "options": ["ORDER BY", "GROUP BY", "WHERE", "JOIN"],
            "answer": "GROUP BY",
        },
        {
            "id": 55,
            "skill": "SQL",
            "topic": "Subqueries",
            "question": "A query written inside another SQL query is called a:",
            "options": ["Subquery", "Join", "Trigger", "Index"],
            "answer": "Subquery",
        },
        {
            "id": 56,
            "skill": "SQL",
            "topic": "Indexes",
            "question": "What is the primary purpose of an index?",
            "options": [
                "Improve query lookup performance",
                "Delete duplicate rows",
                "Create tables automatically",
                "Encrypt the database",
            ],
            "answer": "Improve query lookup performance",
        },
        {
            "id": 57,
            "skill": "SQL",
            "topic": "Aggregate Functions",
            "question": "Which function counts rows?",
            "options": ["COUNT()", "SUM()", "AVG()", "ROWS()"],
            "answer": "COUNT()",
        },
        {
            "id": 58,
            "skill": "SQL",
            "topic": "Joins",
            "question": "Which JOIN returns every combination of rows from two tables?",
            "options": ["INNER JOIN", "CROSS JOIN", "LEFT JOIN", "RIGHT JOIN"],
            "answer": "CROSS JOIN",
        },
        {
            "id": 59,
            "skill": "SQL",
            "topic": "Subqueries",
            "question": "Which operator can compare a value against multiple values returned by a subquery?",
            "options": ["IN", "LIKE", "AS", "ORDER"],
            "answer": "IN",
        },
        {
            "id": 60,
            "skill": "SQL",
            "topic": "Indexes",
            "question": "An index generally improves reads but can add overhead to:",
            "options": [
                "INSERT, UPDATE and DELETE operations",
                "SELECT only",
                "Database startup only",
                "Table naming",
            ],
            "answer": "INSERT, UPDATE and DELETE operations",
        },
    ],

    "React": [
        {
            "id": 61,
            "skill": "React",
            "topic": "Hooks",
            "question": "Which React Hook is used to manage component state?",
            "options": ["useEffect", "useState", "useMemo", "useRef"],
            "answer": "useState",
        },
        {
            "id": 62,
            "skill": "React",
            "topic": "Hooks",
            "question": "Which Hook is commonly used for side effects?",
            "options": ["useEffect", "useState", "useContext", "useReducer"],
            "answer": "useEffect",
        },
        {
            "id": 63,
            "skill": "React",
            "topic": "Forms",
            "question": "A controlled input in React gets its value from:",
            "options": ["Component state", "The browser only", "CSS", "The URL"],
            "answer": "Component state",
        },
        {
            "id": 64,
            "skill": "React",
            "topic": "API Integration",
            "question": "Which HTTP method is commonly used to retrieve data from an API?",
            "options": ["GET", "POST", "DELETE", "PATCH"],
            "answer": "GET",
        },
        {
            "id": 65,
            "skill": "React",
            "topic": "React Project Practice",
            "question": "Why are keys used when rendering lists in React?",
            "options": [
                "To help React identify list items",
                "To add CSS",
                "To make API calls",
                "To define routes",
            ],
            "answer": "To help React identify list items",
        },
        {
            "id": 66,
            "skill": "React",
            "topic": "Hooks",
            "question": "Which Hook can memoize a calculated value?",
            "options": ["useMemo", "useEffect", "useState", "useId"],
            "answer": "useMemo",
        },
        {
            "id": 67,
            "skill": "React",
            "topic": "Forms",
            "question": "Which event is commonly used to handle text input changes?",
            "options": ["onChange", "onClickOnly", "onRoute", "onRender"],
            "answer": "onChange",
        },
        {
            "id": 68,
            "skill": "React",
            "topic": "API Integration",
            "question": "Which library is commonly used in React applications to make HTTP requests?",
            "options": ["Axios", "Lucide", "Vite", "React Router only"],
            "answer": "Axios",
        },
        {
            "id": 69,
            "skill": "React",
            "topic": "React Project Practice",
            "question": "What is JSX?",
            "options": [
                "A syntax extension for JavaScript",
                "A database language",
                "A CSS framework",
                "A backend server",
            ],
            "answer": "A syntax extension for JavaScript",
        },
        {
            "id": 70,
            "skill": "React",
            "topic": "Hooks",
            "question": "Hooks are primarily used in React to:",
            "options": [
                "Use state and other React features in functional components",
                "Create SQL tables",
                "Compile Java code",
                "Replace HTML completely",
            ],
            "answer": "Use state and other React features in functional components",
        },
    ],

    "Git": [
        {
            "id": 71,
            "skill": "Git",
            "topic": "Git Basics",
            "question": "Which command initializes a Git repository?",
            "options": ["git init", "git start", "git create", "git repo"],
            "answer": "git init",
        },
        {
            "id": 72,
            "skill": "Git",
            "topic": "Git Basics",
            "question": "Which command shows the current working tree status?",
            "options": ["git status", "git check", "git info", "git state"],
            "answer": "git status",
        },
        {
            "id": 73,
            "skill": "Git",
            "topic": "Branches",
            "question": "Which command creates a new Git branch?",
            "options": ["git branch feature", "git new feature", "git create feature", "git fork feature"],
            "answer": "git branch feature",
        },
        {
            "id": 74,
            "skill": "Git",
            "topic": "Merge and Rebase",
            "question": "Which command combines changes from another branch into the current branch?",
            "options": ["git merge", "git combine", "git join", "git attach"],
            "answer": "git merge",
        },
        {
            "id": 75,
            "skill": "Git",
            "topic": "Conflict Resolution",
            "question": "A merge conflict usually occurs when:",
            "options": [
                "Git cannot automatically reconcile conflicting changes",
                "The repository is empty",
                "A commit has no message",
                "The branch has no name",
            ],
            "answer": "Git cannot automatically reconcile conflicting changes",
        },
        {
            "id": 76,
            "skill": "Git",
            "topic": "Remote Repositories",
            "question": "Which command uploads local commits to a remote repository?",
            "options": ["git push", "git upload", "git send", "git publish"],
            "answer": "git push",
        },
        {
            "id": 77,
            "skill": "Git",
            "topic": "Remote Repositories",
            "question": "Which command downloads changes from a remote repository and integrates them?",
            "options": ["git pull", "git download", "git sync-only", "git receive"],
            "answer": "git pull",
        },
        {
            "id": 78,
            "skill": "Git",
            "topic": "Git Basics",
            "question": "Which command creates a commit?",
            "options": ["git commit", "git save", "git snapshot", "git record"],
            "answer": "git commit",
        },
        {
            "id": 79,
            "skill": "Git",
            "topic": "Branches",
            "question": "Why are branches useful?",
            "options": [
                "They allow isolated lines of development",
                "They delete the main repository",
                "They replace commits",
                "They prevent collaboration",
            ],
            "answer": "They allow isolated lines of development",
        },
        {
            "id": 80,
            "skill": "Git",
            "topic": "Remote Repositories",
            "question": "Which command downloads remote commits without merging them into the current branch?",
            "options": ["git fetch", "git pull", "git download", "git receive"],
            "answer": "git fetch",
        },
    ],

    "GitHub": [
        {
            "id": 81,
            "skill": "GitHub",
            "topic": "Repositories",
            "question": "What is a GitHub repository primarily used for?",
            "options": [
                "Hosting and collaborating on project code",
                "Only sending emails",
                "Creating operating systems",
                "Running SQL queries only",
            ],
            "answer": "Hosting and collaborating on project code",
        },
        {
            "id": 82,
            "skill": "GitHub",
            "topic": "README Documentation",
            "question": "What is the purpose of a README file?",
            "options": [
                "Explain the project and how to use it",
                "Store passwords",
                "Compile code",
                "Replace Git",
            ],
            "answer": "Explain the project and how to use it",
        },
        {
            "id": 83,
            "skill": "GitHub",
            "topic": "Issues",
            "question": "GitHub Issues are commonly used to:",
            "options": [
                "Track bugs, tasks and feature requests",
                "Compile applications",
                "Store database tables",
                "Create CSS files",
            ],
            "answer": "Track bugs, tasks and feature requests",
        },
        {
            "id": 84,
            "skill": "GitHub",
            "topic": "Pull Requests",
            "question": "A pull request is mainly used to:",
            "options": [
                "Propose and review changes before merging",
                "Delete a repository",
                "Install dependencies",
                "Run a database",
            ],
            "answer": "Propose and review changes before merging",
        },
        {
            "id": 85,
            "skill": "GitHub",
            "topic": "GitHub Actions",
            "question": "GitHub Actions is primarily used for:",
            "options": [
                "Automating workflows such as CI/CD",
                "Designing UI icons",
                "Writing SQL queries",
                "Managing local RAM",
            ],
            "answer": "Automating workflows such as CI/CD",
        },
        {
            "id": 86,
            "skill": "GitHub",
            "topic": "Repositories",
            "question": "A fork creates:",
            "options": [
                "A copy of a repository under another account",
                "A new programming language",
                "A database connection",
                "A local CPU process",
            ],
            "answer": "A copy of a repository under another account",
        },
        {
            "id": 87,
            "skill": "GitHub",
            "topic": "README Documentation",
            "question": "Which information is especially useful in a project README?",
            "options": [
                "Setup and usage instructions",
                "Private API keys",
                "Database passwords",
                "Personal authentication tokens",
            ],
            "answer": "Setup and usage instructions",
        },
        {
            "id": 88,
            "skill": "GitHub",
            "topic": "Issues",
            "question": "What can be assigned to a GitHub Issue?",
            "options": ["A collaborator", "A database", "A compiler", "A CSS selector"],
            "answer": "A collaborator",
        },
        {
            "id": 89,
            "skill": "GitHub",
            "topic": "Pull Requests",
            "question": "Code review on a pull request helps teams:",
            "options": [
                "Identify issues before merging changes",
                "Remove version control",
                "Disable branches",
                "Delete commit history",
            ],
            "answer": "Identify issues before merging changes",
        },
        {
            "id": 90,
            "skill": "GitHub",
            "topic": "GitHub Actions",
            "question": "A GitHub Actions workflow can be triggered by:",
            "options": [
                "Repository events such as pushes",
                "Only keyboard input",
                "Only database changes",
                "Only operating system boot",
            ],
            "answer": "Repository events such as pushes",
        },
    ],

    "REST API": [
        {
            "id": 91,
            "skill": "REST API",
            "topic": "HTTP Methods",
            "question": "Which HTTP method is commonly used to retrieve a resource?",
            "options": ["GET", "POST", "PUT", "DELETE"],
            "answer": "GET",
        },
        {
            "id": 92,
            "skill": "REST API",
            "topic": "HTTP Methods",
            "question": "Which HTTP method is commonly used to create a new resource?",
            "options": ["GET", "POST", "DELETE", "HEAD"],
            "answer": "POST",
        },
        {
            "id": 93,
            "skill": "REST API",
            "topic": "REST Principles",
            "question": "REST APIs are generally designed around:",
            "options": [
                "Resources and representations",
                "Only database tables",
                "Only HTML pages",
                "Only local files",
            ],
            "answer": "Resources and representations",
        },
        {
            "id": 94,
            "skill": "REST API",
            "topic": "Request and Response",
            "question": "Which format is commonly used for REST API request and response bodies?",
            "options": ["JSON", "EXE", "PNG", "MP3"],
            "answer": "JSON",
        },
        {
            "id": 95,
            "skill": "REST API",
            "topic": "Status Codes",
            "question": "What does HTTP status code 404 normally indicate?",
            "options": [
                "Resource not found",
                "Successful request",
                "Server started",
                "Unauthorized only",
            ],
            "answer": "Resource not found",
        },
        {
            "id": 96,
            "skill": "REST API",
            "topic": "Status Codes",
            "question": "What does HTTP status code 200 normally indicate?",
            "options": [
                "Successful request",
                "Not found",
                "Server error",
                "Unauthorized",
            ],
            "answer": "Successful request",
        },
        {
            "id": 97,
            "skill": "REST API",
            "topic": "Authentication",
            "question": "What is authentication used for?",
            "options": [
                "Verifying the identity of a user or client",
                "Sorting data",
                "Compressing JSON",
                "Creating database indexes",
            ],
            "answer": "Verifying the identity of a user or client",
        },
        {
            "id": 98,
            "skill": "REST API",
            "topic": "HTTP Methods",
            "question": "Which HTTP method is commonly used to remove a resource?",
            "options": ["DELETE", "REMOVE", "DROP", "CLEAR"],
            "answer": "DELETE",
        },
        {
            "id": 99,
            "skill": "REST API",
            "topic": "Status Codes",
            "question": "What does HTTP status code 401 generally indicate?",
            "options": [
                "Authentication is required or invalid",
                "Resource created",
                "Request succeeded",
                "Server unavailable only",
            ],
            "answer": "Authentication is required or invalid",
        },
        {
            "id": 100,
            "skill": "REST API",
            "topic": "Request and Response",
            "question": "Which HTTP header is commonly used to specify the media type of a request body?",
            "options": ["Content-Type", "User-Agent", "Host", "Accept-Language"],
            "answer": "Content-Type",
        },
    ],
}


def get_questions(skill: str) -> List[dict]:
    """Return all assessment questions for a skill."""
    return ASSESSMENT_QUESTIONS.get(skill.strip(), [])


def get_available_skills() -> List[str]:
    """Return skills that have assessment questions."""
    return list(ASSESSMENT_QUESTIONS.keys())